### ISSUE TITLE
Test and pre-commit need to be reviewed

### ISSUE THREAD

**Issue by arashmad** [FernLab/cookiecutter-fastapi-package#8]
After testing generated project for FastAPI package, I came across following issues/questions:

- [x] Output report from command `make lint` for generated instance is not informative enough.
When `pre-commit ` command is executed using `make lint`, it generates a report in a text format but there is no information about files and lines, where errors are raised. I think having this information would be necessary to see it and understand the problem.
- [x] As `lint` in **Makefile** , executes `pre-commit` and because of using `--fix` flag in  `{{cookiecutter.project_slug}}/.pre-commit-config.yaml`, it shows that errors were fixed. The problem is, when I run command `make lint`, it means I'm working in local repository  and I may need to continue coding and don't want to push the changes. In these case displaying message that "Error fixed" is misleading I would say because there are still there. The other issue is, even if I accept these fixes, they are not applied in code, because I'm still working on code and next I will get these errors. As we don't know the files/lines, where errors happen, it's hard (sometimes not possible) to track them.
- [x] Python version in `{{cookiecutter.project_slug}}/.pre-commit-config.yaml` file is pinned to **13.3** and if someone uses environment with **python 3.12**, test crashes.

**Comment by arashmad** [comment]
For your consideration 🙏
@romulogoncalves
@jo-kno
@DaRa42

**Comment by romulogoncalves** [comment]
@arashmad you should align with the latest changes at the Python cookiecutter. @Jen-Wenzel can assist you in case you have questions. With the latest changes, I think all the issues/questions in this issue will be covered.

**Comment by romulogoncalves** [comment]
@arashmad is this solved by #9?

**Comment by arashmad** [comment]
@romulogoncalves Yes! Already fixed. I will close it after merging to the main.
